server {
    listen 80;
    server_name 13.124.100.87; # 서버 IP 또는 도메인

    # React 앱과 카카오 리다이렉트 처리
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # 백엔드 API 프록시
    location /api {
        proxy_pass http://localhost:8080; # localhost 사용 권장
        proxy_http_version 1.1;
    }
} 